services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    volumes:
      - /home/ubuntu/hopsakee-server/config/authelia:/config
      - /data/authelia:/data/authelia
      - /data/authelia/secrets:/secrets
    environment:
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_encryption_key
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/secrets/smtp_password
      - AUTHELIA_NOTIFIER_SMTP_USERNAME=jfdejong@gmail.com
    networks:
      - hup

networks:
  hup:
    external: true
