server:
  address: 'tcp://0.0.0.0:9091'

identity_validation:
  reset_password: {}

session:
  cookies:
    - domain: hopsakee.top
      authelia_url: https://auth.hopsakee.top

storage:
  local:
    path: /data/authelia/db.sqlite3

authentication_backend:
  file:
    path: /data/authelia/users_database.yml

notifier:
  smtp:
    address: 'smtp://smtp.gmail.com:587'
    sender: jfdejong@gmail.com

access_control:
  default_policy: deny
  rules:
    - domain: auth.hopsakee.top
      policy: bypass
    - domain: infoflow.hopsakee.top
      policy: one_factor
      subject:
        - ['group:me', 'group:admins']
    - domain: datalab-knowledge.hopsakee.top
      policy: one_factor
      subject:
        - ['group:me', 'group:work', 'group:admins']
    - domain: govchat.hopsakee.top
      policy: one_factor
      subject:
        - ['group:me', 'group:work', 'group:admins']
    - domain: netflix-movies.hopsakee.top
      policy: one_factor
      subject:
        - ['group:me', 'group:friends', 'group:admins']
