hostname: tps-server
preserve_hostname: false

users:
- name: ubuntu
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6iRmXFvXszceaTTGDidkMVSkE2n0nQCSizawR3e2GncxGyBjEy2/5ECFo2AYaJPgyJHjMjmTCevHluXoIo6zd1MRwXomagfmOwEUUQh/Fw28A9swACsnPt6189gRSnqcXhY94jvBTxOOYi1a9RP9o8TtBOkkjFVQvHLgeD5I6R9dJ8aDEuGjg5p2BsJCtyLgvLvB7DxWwPXhSt+0sKlozhCNAZ1rlrIfwxdnvOrIUMkRPmpCL4GymNDIJG21y5Q2NyIVfmmul1uGpz/waw4KKDBDCWd6kMb1QxoXURMQCVYX7pqJ/6UZXt8bzusggwVOjUOKszwWxVAGqYIhrRxVs/hmJN/BJUFFNpN+VztmJeg8l1a99QnoR/F/EjhSzgce0fFdc+ffpNbBKSKtZYbIPjG7EYTGK+tRNX4Fa6A63iR1yy91GlKsVEpESPVeZqsmwegPoiXIHKTWXuAOeaq3HZjhsfNZBSKPI5IF9HtmbCRqp7tNFKbsqCMLT2VGHxzs= jelle@Sledge
  sudo:
  - ALL=(ALL) NOPASSWD:ALL

package_update: true

packages:
- git
- curl
- wget
- neovim
- tree
- ca-certificates
- tmux
- sqlite3
- btop
- ripgrep

runcmd:
- |
  # Install uv
  sudo -u ubuntu -H bash << EOF
  curl -LsSf https://astral.sh/uv/install.sh | sh
  EOF
- |
  # Install Docker
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  # add user ubuntu to docker group, to prevent needing to use sudo for every docker command
  usermod -aG docker ubuntu
  # add docker network with name 'hup' so docker containers can talk to each other by container name
  docker network create hup
- |
  # Clone hopsakee-server
  sudo -u ubuntu  -H bash << EOF
  git clone https://github.com/Hopsakee/hopsakee-server.git
  EOF
- |
  # Install shellsage
  uv tool install shell_sage
