services:

  infoflow:
    image: infoflow
    container_name: infoflow
    restart: unless-stopped
    build: /home/ubuntu/apps/infoflow
    networks:
      - hup
    volumes:
      - /mnt/HC_Volume_105122334:/data

networks:
  hup:
    external: true
